name: masla_bolo_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  get_thumbnail_video: ^0.6.1
  flutter_image_compress: ^2.3.0
  google_fonts: ^6.2.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  intl: ^0.19.0
  fancy_shimmer_image: ^2.0.3
  flutter_screenutil: ^5.9.3
  adaptive_theme: ^3.6.0
  gap: ^3.0.1
  loader_overlay: ^4.0.1
  image_picker: ^1.1.2
  shimmer: ^3.0.0
  geolocator: ^13.0.1
  multiselect: ^0.1.1
  shared_preferences: ^2.3.1
  device_preview: ^1.2.0
  get_it: ^7.7.0
  permission_handler: ^11.3.1
  connectivity_plus: ^6.0.5
  pretty_dio_logger: ^1.4.0
  csc_picker: ^0.2.7
  dropdown_button2: ^2.3.9
  dartz: ^0.10.1
  cached_network_image: ^3.4.0
  equatable: ^2.0.5
  nested: ^1.0.0
  collection: ^1.18.0
  photo_view: ^0.15.0
  dio: ^5.6.0
  flutter_typeahead: ^5.2.0
  flutter_switch: ^0.3.2
  audioplayers: ^6.1.0
  firebase_core: ^3.6.0
  firebase_storage: ^12.3.3
  firebase_auth: ^5.3.1
  google_sign_in: ^6.2.1
  web_socket_channel: ^3.0.1
  firebase_messaging: ^15.1.3
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.11
  flutter_map: ^8.1.1
  latlong2: ^0.9.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/

  fonts:
    - family: Varela
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
    - family: dmSans
      fonts:
      - asset: assets/fonts/DMSans-Regular.ttf
